config/routes.rb
Rails.application.routes.draw do

  root 'questions#random'

  resources :questions, only: :show do
    get :random, to: :random
    resource :solution, only: :show
  end

  devise_for :admins

end

app/models/admin.rb
class Admin < ActiveRecord::Base

  devise :database_authenticatable, :rememberable, :trackable, :timeoutable

end

app/models/question.rb
class Question < ActiveRecord::Base

  has_one :solution

  serialize :test_cases, JSON

  def self.random
    i = Random.rand(count) + 1
    Question.find_by_number(i)
  end

  def self.number(i)
    Question.find_by_number(i)
  end
end

app/models/solution.rb
class Solution < ActiveRecord::Base

  belongs_to :question

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_action :authenticate_admin!

  def random
    redirect_to action: :show, id: Question.random.number
  end

  def show
    @questions = Question.all
    @question = Question.number(params[:id])
  end
end

app/controllers/solutions_controller.rb
class SolutionsController < ApplicationController

  def show
    @questions = Question.all
    @question = Question.find_by_number(params[:question_id])
    @solution = @question.solution
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/index.html.erb
<h2><%= @question.name %></h2>
<p><%= @question.content %></p>

<h3>Test Cases:</h3>

<% if @question.format == 'bullet' %>

  <% @question.test_cases.each do |input, output| %>
    <ul>
      <li><b>Input</b>&nbsp;<%= input %></li>
      <li><b>Output</b>&nbsp;<%= output %></li>
    </ul>
  <% end %>

<% elsif @question.format == 'raw' %>

  <b>Input</b><br/>
  <% @question.test_cases.first.each do |i| %>
    <%= i %><br/>
  <% end %>

  <br/>

  <b>Output</b><br/>
  <% @question.test_cases.last.each do |o| %>
    <%= o %><br/>
  <% end %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GhcInterview</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class='header page-header row'>
    <div class='col-md-6' style='text-align:left'>
      <% if @question && @questions %>

        <%= link_to_unless @question == Question.first, '<<', question_path(@question.number - 1) %>

        <% @questions.each do |q| %>
          <% if q.id == @question.id %>
            <b><u><%= link_to q.number, question_path(q.number) %></u></b>
          <% else %>
            <%= link_to q.number, question_path(q.number) %>
          <% end %>
        <% end %>

        <%= link_to_unless @question == Question.last, '>>', question_path(@question.number + 1) %>
        &nbsp;
        <%= link_to 'random', root_path %>
        &nbsp;
        <% if @solution %>
          <b><u><%= link_to 'solution', question_solution_path(@question.number) %></u></b>
        <% else %>
          <%= link_to 'solution', question_solution_path(@question.number) %>
        <% end %>
      <% end %>
    </div>

    <div class='col-md-6' style='text-align:right'>
      <%= link_to 'Sign In', new_admin_session_path %>
      &nbsp;
      <%= link_to 'Sign Out', destroy_admin_session_path, method: :delete %>
    </div>
  </div>

  <%= yield %>

</body>
</html>

app/views/questions/show.html.erb
<h2><%= @question.name %></h2>
<p><%= @question.content %></p>

<h3>Test Cases:</h3>

<% if @question.format == 'bullet' %>

  <% @question.test_cases.each do |input, output| %>
    <ul>
      <li><b>Input</b>&nbsp;<%= input %></li>
      <li><b>Output</b>&nbsp;<%= output %></li>
    </ul>
  <% end %>

<% elsif @question.format == 'raw' %>

  <b>Input</b><br/>
  <% @question.test_cases.first.each do |i| %>
    <%= i %><br/>
  <% end %>

  <br/>

  <b>Output</b><br/>
  <% @question.test_cases.last.each do |o| %>
    <%= o %><br/>
  <% end %>

<% end %>

app/views/solutions/show.html.erb
<h2><%= @question.name %></h2>

<h3>Solution:</h3>

<p><%= raw(@solution.code.gsub("\n", "<br/>").gsub(/[\s]{2}/, "&nbsp;&nbsp;&nbsp;&nbsp;")) %></p>